name: Label issues

on:
  issues:
    types:
      - reopened
      - opened
      - closed
      - assigned

env:
  PROJECT_NAME: TODO

jobs:
  dump_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
  issue_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add backlog label
        if: "github.event.action == 'opened'"
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "Status: Backlog"
          remove-labels: "Status: Closed"
      - name: Add inprogress label
        if: "github.event.action == 'assigned' || github.event.action == 'reopened'"
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "Status: In Progress"
          remove-labels: "Status: Backlog, Status: Closed"
      - name: Add close label
        if: "github.event.action == 'closed'"
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "Status: Closed"
          remove-labels: "Status: Backlog, Status: In Progress"
      - name: Add feat label
        if: "github.event.action == 'opened' && startsWith(github.event.issue.title, 'feat')"
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "Type: Feature"
      - name: Add bug label
        if: "github.event.action == 'opened' && startsWith(github.event.issue.title, 'bug') || startsWith(github.event.issue.title, 'fix')"
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "Type: Bug"
      - name: Add ci label
        if: "github.event.action == 'opened' && startsWith(github.event.issue.title, 'ci')"
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "Type: CI"
      - name: Add test label
        if: "github.event.action == 'opened' && startsWith(github.event.issue.title, 'test')"
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "Type: Testing"

  assign_issue_to_project:
    name: Assign issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to project
        uses: technote-space/create-project-card-action@v1
        if: "github.event.action == 'opened'"
        with:
          PROJECT: ${{env.PROJECT_NAME}}
          COLUMN: 未処理
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  move_assigned_card:
    runs-on: ubuntu-latest
    name: Move assigned card
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: "github.event.action == 'assigned'"
        with:
          project: ${{env.PROJECT_NAME}}
          column: 進行中 or 作業中Issue・Pull Request
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: "github.event.action == 'reopened'"
        with:
          project: ${{env.PROJECT_NAME}}
          column: 進行中 or 作業中Issue・Pull Request
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  move_the_card_when_the_issue_is_closed:
    runs-on: ubuntu-latest
    name: Move the card when the issue is closed
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: "github.event.action == 'closed'"
        with:
          project: ${{env.PROJECT_NAME}}
          column: 完了済み
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}